GameProject/Controllers/CategoryController.cs
using Game.BL.DTO;
using Game.BL.Interface;
using Microsoft.AspNetCore.Mvc;

namespace GameProject.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        [Route("/")]
        public async Task<IActionResult> Index()
        {
            var categories=await _categoryService.GetCategories();
            return View(categories?.AsEnumerable());
        }
        public IActionResult Add()
        {
            var model = new AddCategoryDTO();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddCategoryDTO category)
        {
           await _categoryService.AddCategory(category);
           return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id) 
        { 
           var category=await _categoryService.GetCategoryById(id);
           return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ViewOrAddCategoryDTO input)
        {
            await _categoryService.UpdateCategory(input);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _categoryService.DeleteCategory(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

GameProject/Controllers/DevicesController.cs
using Game.BL.DTO;
using Game.BL.Interface;
using Microsoft.AspNetCore.Mvc;

namespace GameProject.Controllers
{
    public class DevicesController : Controller
    {
        private readonly IDeviceService _deviceService;
        public DevicesController(IDeviceService deviceService)
        {
            _deviceService = deviceService;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _deviceService.GetDevicesAsQueryable();
            return View(model);
        }
        public IActionResult Add()
        {
            var model = new DeviceDTO();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Add(DeviceDTO device)
        {
            await _deviceService.AddOrEditDevice(device);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var model=await _deviceService.GetDeviceById(id);   
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(DeviceDTO device)
        {
            await _deviceService.AddOrEditDevice(device);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _deviceService.DeleteDevice(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

GameProject/Controllers/GamesController.cs
using Game.BL.DTO;
using Game.BL.Interface;
using GameZone.Settings;
using Microsoft.AspNetCore.Mvc;

namespace GameProject.Controllers
{
    public class GamesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IDeviceService _deviceService;
        private readonly IGameService _gameService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public GamesController(IWebHostEnvironment webHostEnvironment,ICategoryService categoryService, IDeviceService deviceService, IGameService gameService)
        {
            _categoryService = categoryService;
            _deviceService = deviceService;
            _gameService = gameService;
            _webHostEnvironment = webHostEnvironment;
            _gameService.Initialize($"{_webHostEnvironment.WebRootPath}{FileSettings.FilePath}");
        }
        
        public async Task<IActionResult> Index()
        {
            var game=await _gameService.GetAllGames();
            return View(game.AsEnumerable());
        }

        [HttpGet]
        public async Task<IActionResult> AddGame()
        {
            CreateGameDTO model = new()
            {
                Categories =await _categoryService.GetSelectListCategories(),
                Devices =await _deviceService.GetSelectListDevices(),
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddGame(CreateGameDTO input)
        {
            if (!ModelState.IsValid)
            {
                input.Categories =await _categoryService.GetSelectListCategories();
                input.Devices=await _deviceService.GetSelectListDevices();
                return View(input);
            }
            await _gameService.GreateGame(input);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var game= await _gameService.GetGame(id);
            return View(game);  
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var game =await _gameService.GetGame(id);
            if (game is null)
                throw new Exception("The Game Not Found");
            EditGameDTO viewModel = new EditGameDTO()
            {
                Id=id,
                Name=game.Name,
                Description=game.Description,
                CategoryId=game.CategoryId,
                SelectedDevices=game.Devices!.Select(d=>d.Id!.Value).ToList(),
                Categories=await _categoryService.GetSelectListCategories(),
                Devices= await _deviceService.GetSelectListDevices(),
                CurrentCover=game.Cover,
            }; 
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditGameDTO input)
        {
            if (!ModelState.IsValid)
            {
                input.Categories = await _categoryService.GetSelectListCategories();
                input.Devices = await _deviceService.GetSelectListDevices();
                return View(input);
            }
            await _gameService.EditGame(input);
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var isDeleted=await _gameService.DeleteGame(id);
            return isDeleted? Ok():BadRequest();
        }
    }
}

GameProject/Views/Category/Add.cshtml
@model AddCategoryDTO
@{
    ViewData["Title"]= "Add Category";
}
<form method="post">
    <input type="text" placeholder="Please Enter Category Name" asp-for="Name" />
    <button type="submit">Add</button>
</form>

GameProject/Views/Category/Edit.cshtml
@model ViewOrAddCategoryDTO
@{
    ViewData["Title"] = "Edit Category";
}
<form method="post">
    <input type="text" placeholder="Please Enter Category Name" asp-for="Name" />
    <button type="submit">Save</button>
</form>

GameProject/Views/Category/Index.cshtml
@model IEnumerable<GetCategoryDTO>
@if(Model is null){
    <p>
        No Any Category To Display;
    </p>
}
else{
    @foreach(var item in Model)
    {
        <p>@item.Name</p>
    }
}

GameProject/Views/Devices/Add.cshtml
@model DeviceDTO
@{
    ViewData["Title"]= "Add Category";
}
<form method="post">
    <input type="text" placeholder="Please Enter Device Name" asp-for="Name" />
    <input type="text" placeholder="Please Enter Device Icon Code" asp-for="DeviceIcon" />
    <button type="submit">Add</button>
</form>

GameProject/Views/Devices/Edit.cshtml
@model DeviceDTO
@{
    ViewData["Title"] = "Add Category";
}
<form method="post">
    <input type="text" placeholder="Please Enter Device Name" asp-for="Id" hidden />
    <input type="text" placeholder="Please Enter Device Name" asp-for="Name" />
    <input type="text" placeholder="Please Enter Device Icon Code" asp-for="DeviceIcon" />
    <script src="~/lib/font-awesome/js/fontawesome.min.js"></script>
    <button type="submit">Save Changes</button>
</form>

GameProject/Views/Devices/Index.cshtml
@model IEnumerable<DeviceDTO>
@if(Model is null){
    <p>
        No Any Category To Display;
    </p>
}
else{
    <table>
        <thead>
            <th>Name</th>
            <th>Description</th>
            <th>Device Icon</th>
        </thead>
        <tr>
        @foreach (var item in Model)
        {
            <td>@item.Name</td>
            <td><i class="@item.DeviceIcon me-2 fs-4"></i></td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>  
        }
        </tr>
    </table>

}
<a asp-controller="Devices" asp-action="Add">Add Device</a>

GameProject/Views/Games/AddGame.cshtml
@using GameZone.Settings;
@using Microsoft.AspNetCore.Mvc.Rendering
@model CreateGameDTO
@{
    ViewData["Title"] = "Add Game"; 
}
@{
    IEnumerable<SelectListItem> Categoryitems = Model.Categories.Select(item => new SelectListItem
            {
                Value = item.Value,
                Text = item.Text
            });
    IEnumerable<SelectListItem> Deviceitems = Model.Devices.Select(item => new SelectListItem
            {
                Value = item.Value,
                Text = item.Text
            });

}
<link href="~/css/site.css" rel="stylesheet" />
<h5> 
    <i class="bi bi-plus-circle-dotted"></i>
    Add a new game
</h5>

<form asp-controller="Games" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="form-label mt-4"></label>
                <select class="form-select select2 select2-container" asp-for="CategoryId" asp-items="Categoryitems"
                    data-placeholder="Select a category">
                    <option value=""></option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectedDevices" class="form-label mt-4"></label>
                <select class="form-select select2 select2-container" asp-for="SelectedDevices" asp-items="Deviceitems"
                        data-placeholder="Select devices">
                    <option></option>
                </select>
                <span asp-validation-for="SelectedDevices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="form-label mt-4"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="form-label mt-4"></label>
                <input type="file" class="form-control" asp-for="Cover" 
                    data-rule-extension="@FileSettings.AllowedExtensions.Replace(".", string.Empty)"
                       data-msg-extension="Not allowed extension">
                <small class="form-text text-muted">Only @FileSettings.AllowedExtensions files are allowed with max size @(FileSettings.MaxFileSizeInMB)MB.</small>
                <span asp-validation-for="Cover" class="text-danger d-block"></span>
            </div>
            <button type="submit" class="btn btn-light text-black mt-4">Save</button>
        </div>
        <div class="col-md-6 d-flex justify-content-center pt-4 overflow-hidden">
            <img class="cover-preview d-none" alt="Cover" />
        </div>
    </div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            $("#Cover").on("change", function () {
                $(".cover-preview").attr('src', window.URL.createObjectURL(this.files[0])).removeClass("d-none");
            });
        });

    </script>
}

GameProject/Views/Games/Details.cshtml
@using GameZone.Settings;
@model GetGameDTO

@{
    ViewData["Title"] = Model.Name; 
}

<div class="card border-success rounded-4 mt-5 overflow-hidden">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-md-8 px-5 py-4 d-flex flex-column justify-content-between">
                <div>
                    <h1 class="text-success fw-bolder">@Model.Name</h1>
                    <span class="badge bg-info fs-5 mb-4">@Model.CategoryName</span>
                    <p class="fs-5">@Model.Description</p>
                </div>
                <div>
                    @foreach (var gameDevice in Model.Devices)
                    {
                        <i class="@gameDevice.DeviceIcon me-2 fs-1 text-secondary"></i>
                    }
                </div>
            </div>
            <div class="col-md-4">
                <img src="@($"{FileSettings.FilePath}/{Model.Cover}")" alt="@Model.Name" class="w-100" style="height:100%" />
            </div>
        </div>
    </div>
</div>

GameProject/Views/Games/Edit.cshtml
@using GameZone.Settings;
@using Microsoft.AspNetCore.Mvc.Rendering
@model EditGameDTO
@{
    ViewData["Title"] = "Add Game";
}
// Your code
@{
    IEnumerable<SelectListItem> Categoryitems = Model.Categories.Select(item => new SelectListItem
            {
                Value = item.Value,
                Text = item.Text
            });
    IEnumerable<SelectListItem> Deviceitems = Model.Devices.Select(item => new SelectListItem
            {
                Value = item.Value,
                Text = item.Text
            });

}

<link href="~/css/site.css" rel="stylesheet" />
<h5>
    <i class="bi bi-plus-circle-dotted"></i>
    Add a new game
</h5>

<form asp-controller="Games" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="form-label mt-4"></label>
                <select class="form-select" asp-for="CategoryId" asp-items="Categoryitems"
                        data-placeholder="Select a category">
                    <option value=""></option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectedDevices" class="form-label mt-4"></label>
                <select class="form-select" asp-for="SelectedDevices" asp-items="Deviceitems"
                        data-placeholder="Select devices">
                    <option></option>
                </select>
                <span asp-validation-for="SelectedDevices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="form-label mt-4"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="form-label mt-4"></label>
                <input type="file" class="form-control" asp-for="Cover"
                       data-rule-extension="@FileSettings.AllowedExtensions.Replace(".", string.Empty)"
                       data-msg-extension="Not allowed extension">
                <small class="form-text text-muted">Only @FileSettings.AllowedExtensions files are allowed with max size @(FileSettings.MaxFileSizeInMB)MB.</small>
                <span asp-validation-for="Cover" class="text-danger d-block"></span>
            </div>
            <button type="submit" class="btn btn-light text-black mt-4">Save</button>
        </div>
        <div class="col-md-6 d-flex justify-content-center pt-4 overflow-hidden">
            <img class="cover-preview" alt="@Model.CurrentCover" src="@($"{FileSettings.FilePath}/{Model.CurrentCover}")"  />
        </div>
    </div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            $("#Cover").on("change", function () {
                $(".cover-preview").attr('src', window.URL.createObjectURL(this.files[0])).removeClass("d-none");
            });
        });

    </script>
}

GameProject/Views/Games/Index.cshtml
@using GameZone.Settings;
@model IEnumerable<GetGameDTO>
@{
    ViewData["Title"] = "Games"; 
}
<a class="btn btn-secondary btn-lg" asp-action="AddGame">
    <i class="bi bi-plus-circle-dotted"></i>
    Add Game
</a>

@if (!Model.Any())
{
    <div class="alert alert-warning mt-5">
        <h4 class="alert-heading">No games!</h4>
        <p class="mb-0">No games were added yet.</p>
    </div>
}
else
{
    <div class="mt-5">
        <table class="table table-bordered border-primary">
            <tbody>
                @foreach(var game in Model)
                {
                    <tr class="border-1 border-success">
                        <td>
                            <div class="d-flex">
                                <div class="pe-4">
                                    <img  src="@($"{FileSettings.FilePath}/{game.Cover}")" alt="@game.Name" style="height:100%;max-width: 90px" />
                                </div>
                                <div class="d-flex flex-column justify-content-center">
                                    <h4 class="text-light">@game.Name</h4>
                                    <h5>@game.CategoryName</h5>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">
                            <div class="d-flex justify-content-end">
                                <a class="btn btn-info rounded rounded-3 me-2" asp-action="Edit" asp-route-id="@game.Id">
                                    <i class="bi bi-pencil-fill"></i>
                                </a>
                                <a href="javascript:;" class="btn btn-danger rounded rounded-3 js-delete" data-id="@game.Id">
                                    <i class="bi bi-trash3"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

@section Scripts
{

@*    <script src="~/js/games-index.js" asp-append-version="true"></script>
*@
<script>
        $(document).ready(function () {
            $('.js-delete').on('click', function () {
                var btn = $(this);
                const swal = Swal.mixin({
                    customClass: {
                        confirmButton: 'btn btn-danger mx-2',
                        cancelButton: 'btn btn-light'
                    },
                    buttonsStyling: false
                });
                swal.fire({
                    title: 'Are you sure that you need to delete this game?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'No, cancel!',
                    reverseButtons: true
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: `/Games/Delete/${btn.data('id')}`,
                            method: 'Delete',
                            success: function () {
                                swal.fire(
                                    'Deleted!',
                                    'Game has been deleted.',
                                    'success'
                                );

                                btn.parents('tr').fadeOut();
                            },
                            error: function () {
                                swal.fire(
                                    'Oooops...',
                                    'Something went wrong.',
                                    'error'
                                );
                            }
                        });
                    }
                });
            });
        });
</script>
}

GameProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameProject.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Gategories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Devices" asp-action="Index">Devices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/select2/js/select2.min.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>